# Generated by Django 3.0.8 on 2021-01-18 19:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('m_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('Mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
