# Generated by Django 3.0.8 on 2021-01-18 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0002_person_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='opd.Person')),
                ('Reg_date', models.DateField()),
            ],
            bases=('opd.person',),
        ),
    ]
